---
- hosts: hdfs_namenode
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml
# https://medium.com/codex/running-a-multi-node-hadoop-cluster-257068e5f276
  tasks:


    - name: Install Jupyter
      ansible.builtin.shell: |
       export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH";
       python -m pip install  notebook \
                              jupyter_nbextensions_configurator \
                              jupyter_contrib_nbextensions \
                              yapf wget
       
      args:
        executable: /bin/bash

    - name: Configure Jupyter Extensions
      ansible.builtin.shell: |
        export PATH="$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH";
        asdf reshim python
        jupyter contrib nbextension install --user
        jupyter nbextensions_configurator enable --user
        jupyter nbextension enable toc2/main
        jupyter nbextension enable codefolding/main
        jupyter nbextension enable execute_time/ExecuteTime 
      args:
        executable: /bin/bash
