---
- hosts: spark_master
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
  - name: Stop Spark
    ignore_errors: yes
    ansible.builtin.shell: |
      {{spark_home_dir}}/sbin/stop-workers.sh
      sleep 2
      {{spark_home_dir}}/sbin/stop-master.sh

    args:
      executable: /bin/bash
