---
- hosts: hdfs_namenode
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
  - name: Start Spark Master
    ansible.builtin.shell: |
      {{spark_home_dir}}/sbin/start-master.sh
    args:
      executable: /bin/bash

  - name: Spark Workers
    ansible.builtin.shell: |
      {{spark_home_dir}}/sbin/start-workers.sh
    args:
      executable: /bin/bash
