---
- hosts: hdfs_namenode
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
  - name: Stop HDFS
    ansible.builtin.shell: |
      {{hadoop_home_dir}}/sbin/start-dfs.sh
      sleep 2
      {{hadoop_home_dir}}/sbin/start-yarn.sh

    args:
      executable: /bin/bash
