---
- hosts: hdfs_namenode
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:
  - name: Stop YARN
    ignore_errors: yes
    ansible.builtin.shell: |
      {{hadoop_home_dir}}/sbin/stop-yarn.sh
    args:
      executable: /bin/bash

  - name: Stop HDFS
    ignore_errors: yes
    ansible.builtin.shell: |
      {{hadoop_home_dir}}/sbin/stop-dfs.sh
    args:
      executable: /bin/bash
