---
- hosts: jupyter_service
  become: no
  any_errors_fatal: true
  gather_facts: no
  vars_files:
      - vars.yaml

  tasks:

    - name: Start Jupyter notebook
      shell: 
        tmux -f {{ default_install_dir }}/tmux.conf new-session -d -s tjupyter "./start_jupyter.sh && exit"
      args:
        chdir: '{{ default_install_dir }}'
        executable: /bin/bash