---
  - name: Get running processes
    shell: "ps -ax | grep -E {{process_to_kill}} | grep -v grep | awk '{print $1}'"
    register: running_processes

  - name: Process to kill
    debug: 
      msg: "{{ running_processes.stdout_lines  }}"
    ignore_errors: yes

  - name: Force kill stuck processes
    become: yes 
    shell: "kill -9 {{ item }}"
    with_items: "{{ running_processes.stdout_lines }}"
    register: out
    failed_when: "not(out.rc == 0 or 'No such process' in out.stderr)"

  - wait_for:
      path: "/proc/{{ item }}/status"
      state: absent
      timeout: 15
    become: yes
    with_items: "{{ running_processes.stdout_lines }}"
